### ISSUE TITLE
Update for Summer 2020-2021 Springboard

### ISSUE THREAD

**Issue by morganjwilliams** [core-skills/05-simple-predictions#4]
We'll need to update a few things for the next iteration of the springboard, including:
- [x] The runsheet and timings (both in AEST and AWST).
- [x] Clearing out old material which is unused currently.
- [x] Checking the environment file.
- [x] Adjusting timings for the first session (previously ~1hr, now ~1.5 hr).

**Comment by cericia** [comment]
Items for day 5 have been addressed. Timings have been adjusted, the environment file has been updated and tested, and data folder has been cleaned up.
